# -*- coding: utf-8 -*-
"""Real estate_price_predictor by data analytics (Advanced Regression).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xt9OotJYUW4fOlRORegt16idAWeBDFw-

Project : Real estate price predictor by data analytics (Advanced Regression)

Author : S M Tanjimul Haque

A US-based housing company named Surprise Housing has decided to enter the Australian market. The company uses data analytics to purchase houses at a price below their actual values and flip them on at a higher price. For the same purpose, the company has collected a data set from the sale of houses in Australia.

The company is looking at prospective properties to buy to enter the market. You are required to build a regression model using regularisation in order to predict the actual value of the prospective properties and decide whether to invest in them or not.

The company wants to know:

    Which variables are significant in predicting the price of a house, and
    How well those variables describe the price of a house.

Steps:
    1. Data understanding
    2. Data preparation
    3. Visualizing the data
    4. Model Building
        4.1 Using Lasso Regression
        4.2 Using Ridge Regression
    5. Inferences and recommendations from above Model
"""

#supressing warnings
import warnings
warnings.filterwarnings('ignore')
#importing necessary libraries to handle data
import numpy as np
import pandas as pd
#importing necessary libraries for visualizing data
import matplotlib.pyplot as plt
import seaborn as sns
#importing necessary libraries to perform Linear, Lasso and Ridge Regression
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
#importing libraries for scaling
from sklearn.preprocessing import StandardScaler
#importing libraries for test train split
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
#importing libraries for Metrics
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

#Reading the dataset provided
housePrice_df = pd.read_csv("train.csv")

# option to view all columns
pd.set_option('display.max_columns',None)
#reading the first 5 rows of data set
housePrice_df.head()

#describing the dataset
housePrice_df.describe()

#shape of the dataframe
housePrice_df.shape

#checking for the duplicate values
any(housePrice_df.duplicated())

"""It is clear that there is no duplicate values present in the dataset.

Lets missing value counts and its percentages at each level of handling the missing values.
"""

# Checking for the missing values
round(100*(housePrice_df.isnull().sum()/len(housePrice_df.index)), 2).sort_values(ascending = False)

"""## Missing Value Treatment

There are three columns are having the more than 80% of missing data values. even if we impute those values with any other value the data will be skewed with one data point and there wont be any variance with these columns. Hence I am droping the columns which are having more than 80% of missing data
"""

#droping the values which are having more than 80% of missing values
housePrice_df.drop(columns=['PoolQC','MiscFeature','Alley','Fence'],inplace=True)

"""Based on the data available in the data description file, we can conclude that if any categorical variable is having Null /Nan values means that variable does not have any value. Hence we are imputing each column with the variables like No Fire Place , and so on."""

#checking again for missing values
round(100*(housePrice_df.isnull().sum()/len(housePrice_df.index)), 2).sort_values(ascending = False)

# imputing nan with 'No Fireplace' value for FireplaceQu
housePrice_df['FireplaceQu'] = housePrice_df['FireplaceQu'].replace(np.nan, 'No Fireplace')
housePrice_df['FireplaceQu'].value_counts(dropna=False)

#checking again for missing values
round(100*(housePrice_df.isnull().sum()/len(housePrice_df.index)), 2).sort_values(ascending = False)

# imputing  Nan values with No Garage for GarageType,GarageFinish,GarageQual,GarageCond
missingGarage=['GarageType','GarageFinish','GarageQual','GarageCond']

for i in missingGarage:
    housePrice_df[i] = housePrice_df[i].replace(np.nan, 'No Garage')
for i in missingGarage:
    print(housePrice_df[i].value_counts())

"""From the above, it seems to be some of these columns are highly correlated and let us find which are highly correlated."""

plt.figure(figsize=(20, 10))

plt.subplot(2,2,1)
plt.title("GarageCond Vs SalePrice")
sns.boxplot(x = 'GarageCond', y = 'SalePrice', data = housePrice_df)

plt.subplot(2,2,2)
plt.title("GarageQual Vs SalePrice")
sns.boxplot(x = 'GarageQual', y = 'SalePrice', data = housePrice_df)

plt.subplot(2,2,3)
plt.title("GarageFinish Vs SalePrice")
sns.boxplot(x = 'GarageFinish', y = 'SalePrice', data = housePrice_df)

plt.subplot(2,2,4)
plt.title("GarageType Vs SalePrice")
sns.boxplot(x = 'GarageType', y = 'SalePrice', data = housePrice_df)

"""From the above, we can see that GarageCond and GarageQual with less variance of the data and highly coorelated. Hence I am droping the two columns."""

#droping the GarageCond and GarageQual
housePrice_df.drop(['GarageCond','GarageQual'],axis=1,inplace=True)

#checking again for missing values
round(100*(housePrice_df.isnull().sum()/len(housePrice_df.index)), 2).sort_values(ascending = False)

# imputing  Nan values with No Basement
missingBasement=['BsmtExposure','BsmtFinType2','BsmtQual','BsmtCond','BsmtFinType1']

for i in missingBasement:
    housePrice_df[i] = housePrice_df[i].replace(np.nan, 'No Basement')
for i in missingBasement:
    print(housePrice_df[i].value_counts())

# due to due to skewness of the data, we are dropping the columns BsmtFinType2 and BsmtCond
housePrice_df.drop(['BsmtFinType2','BsmtCond'],axis=1,inplace=True)

#plotting between the missing basement and target variable(Saleprice)
plt.figure(figsize=(20, 10))
plt.subplot(1,3,1)
plt.title("BsmtFinType1 Vs SalePrice")
sns.boxplot(x = 'BsmtFinType1', y = 'SalePrice', data = housePrice_df)
plt.subplot(1,3,2)
plt.title("BsmtQual Vs SalePrice")
sns.boxplot(x = 'BsmtQual', y = 'SalePrice', data = housePrice_df)
plt.subplot(1,3,3)
plt.title("BsmtExposure Vs SalePrice")
sns.boxplot(x = 'BsmtExposure', y = 'SalePrice', data = housePrice_df)

# BsmtFinType1 not having importance in the sale price Hence droping the column
housePrice_df.drop("BsmtFinType1",axis=1,inplace=True)

#Checking for value Counts for Electrical
housePrice_df['Electrical'].value_counts(dropna=False)

#The above column is having more skewness of the data hence we are droping the column.
housePrice_df.drop("Electrical",axis=1,inplace=True)

#checking again for missing values
round(100*(housePrice_df.isnull().sum()/len(housePrice_df.index)), 2).sort_values(ascending = False)

"""### Handling Missing values for contineous variables"""

#imputing Median for LotFrontage as it the data is having some outliers too.
housePrice_df['LotFrontage'].fillna(housePrice_df['LotFrontage'].median(),inplace=True)
housePrice_df['LotFrontage'].value_counts(dropna=False)

# imputing  Nan with None for MasVnrType
housePrice_df['MasVnrType'] = housePrice_df['MasVnrType'].replace(np.nan, 'None')
housePrice_df['MasVnrType'].value_counts(dropna=False)

sns.boxplot(x='MasVnrArea', data=housePrice_df)

housePrice_df['MasVnrArea'].describe()

# Since there are some outliers are present in the data for the MasVnrType we imputing  Nan with Median for MasVnrType
housePrice_df['MasVnrArea'].fillna(housePrice_df['MasVnrArea'].median(),inplace=True)
housePrice_df['MasVnrArea'].value_counts(dropna=False)

"""GarageYrBlt is similar as YearBuilt thus there will be high correaltion betweent the two. Hence we are droping the column.
Droping the Month sold as it will not represent in the inferences of the model hence droping the column
"""

housePrice_df.drop(['GarageYrBlt','MoSold'],axis=1,inplace=True)

#checking again for missing values
round(100*(housePrice_df.isnull().sum()/len(housePrice_df.index)), 2).sort_values(ascending = False)

"""Since there is no missing values Then we will proceed further."""

# Formatting the years to number of years
housePrice_df['HouseAge']= 2020-housePrice_df['YearBuilt']
housePrice_df['House_RemodelAge']= 2020-housePrice_df['YearRemodAdd']

#Droping the Id Column as it is unique.
housePrice_df.drop("Id", axis = 1, inplace = True)

"""## EDA

In this section we will try to explore the relation between independent variables and target variable i.e., Sale price.
First we will perform the Heat map
"""

# figure size
plt.figure(figsize=(25,20))
# heatmap
sns.heatmap(housePrice_df.corr(), cmap="YlGnBu", annot=True)

"""From the above correaltion map, we can observe that few columns are having postive correalation with the target variable and few variables are having negative correaltion with the target variable.

Target variable(Sale Price) is positive correlated with:
    
    OverallQual - Overall Quality of the House
    TotalBasmtSF - Total Basement area in SQFT
    1stFlrSF  - First Floor Area in SQFT
    GrLivArea  - Total Area above ground living in SQFT
    GarageCars  - Size of the Garage(Number of cars)
    GarageArea  - Total area of Garage in SQFT

Target variable(Sale Price) is negatively correlated with:

    HouseAge  - Age of the property
    House_RemodelAge  - Age of the property after remodelling done

## Checking the target variable distribution
"""

#Plotting dist plot:
plt.figure(figsize=(10,5))
sns.distplot(housePrice_df['SalePrice'])

"""Since the target variable is not normally distributed, hence we need to convert the target variable to log of target variable"""

housePrice_df['SalePrice'] = np.log(housePrice_df['SalePrice'])

#Plotting dist plot:
plt.figure(figsize=(10,5))
sns.distplot(housePrice_df['SalePrice'])

#Dropping columns with skewed data  and highly correlated with other and columns which are not having business impact
housePrice_df.drop(['MSZoning','Street','LandContour','Utilities','Condition2','Condition1','LandSlope','RoofMatl','ExterCond',
              'Heating','Functional','PavedDrive','BldgType','BsmtHalfBath','KitchenAbvGr','SaleType','SaleCondition','BsmtFinSF1','BsmtUnfSF']
             ,axis=1, inplace=True)

#Extracting numerical / contineous variables for further analysis
num_var= [i for i in housePrice_df.columns if housePrice_df.dtypes[i]!='object']
cat_var = [i for i in housePrice_df.columns if housePrice_df.dtypes[i] =='object']

cat_var

for i in cat_var:
    print(i,housePrice_df[i].unique(),'\n')

"""### converting columns into binary values"""

# Mapping Central Air to binary values
housePrice_df['CentralAir'] = housePrice_df['CentralAir'].replace({'N': 0, 'Y': 1})

#Checking for value Counts for Neighborhood
housePrice_df['Neighborhood'].value_counts(dropna=False)

# Combining value counts less than 30 into Others for Neibhourhood
housePrice_df['Neighborhood'].replace({'ClearCr':'Others'},inplace=True)
housePrice_df['Neighborhood'].replace({'StoneBr':'Others'},inplace=True)
housePrice_df['Neighborhood'].replace({'SWISU':'Others'},inplace=True)
housePrice_df['Neighborhood'].replace({'MeadowV':'Others'},inplace=True)
housePrice_df['Neighborhood'].replace({'Blmngtn':'Others'},inplace=True)
housePrice_df['Neighborhood'].replace({'BrDale':'Others'},inplace=True)
housePrice_df['Neighborhood'].replace({'Veenker':'Others'},inplace=True)
housePrice_df['Neighborhood'].replace({'NPkVill':'Others'},inplace=True)
housePrice_df['Neighborhood'].replace({'Blueste':'Others'},inplace=True)

#Based on the data description, There are few variables are in numerical but actually they are categorical.
#converting them into categorical variables
housePrice_df['MSSubClass'] = housePrice_df['MSSubClass'].astype('object')
housePrice_df['OverallQual'] = housePrice_df['OverallQual'].astype('object')
housePrice_df['OverallCond'] = housePrice_df['OverallCond'].astype('object')
housePrice_df['BsmtFullBath'] = housePrice_df['BsmtFullBath'].astype('object')
housePrice_df['FullBath'] = housePrice_df['FullBath'].astype('object')
housePrice_df['HalfBath'] = housePrice_df['HalfBath'].astype('object')
housePrice_df['BedroomAbvGr'] = housePrice_df['BedroomAbvGr'].astype('object')
housePrice_df['TotRmsAbvGrd'] = housePrice_df['TotRmsAbvGrd'].astype('object')
housePrice_df['Fireplaces'] = housePrice_df['Fireplaces'].astype('object')
housePrice_df['GarageCars'] = housePrice_df['GarageCars'].astype('object')

"""### Creating Dummy Variables"""

# Creating Dummy variables for categorical variables
cat_var_df = housePrice_df.select_dtypes(include=['object'])
# converting categorical variables in dummy variables
cat_dummies = pd.get_dummies(cat_var_df, drop_first=True)
#reading the top 5 rows
cat_dummies.head()

# concatenating dummy variable dataframe into original dataframe.
housePrice_df = pd.concat([housePrice_df, cat_dummies], axis=1)
housePrice_df.shape

# Dropping the original categorical columns.
housePrice_df.drop(['MSSubClass','LotShape','LotConfig','Neighborhood','HouseStyle','OverallQual','OverallCond','RoofStyle',
              'Exterior1st','Exterior2nd','MasVnrType','ExterQual','Foundation','BsmtQual','BsmtExposure','HeatingQC',
              'BsmtFullBath','FullBath','HalfBath','BedroomAbvGr','KitchenQual','TotRmsAbvGrd','Fireplaces',
              'FireplaceQu','GarageType','GarageFinish','GarageCars'],axis=1,inplace=True)
housePrice_df.shape

# Creating dataframe for  for contineous variables
num_var_df=housePrice_df.select_dtypes(include =['int64','float64'])
#reading the top 5 rows
num_var_df.head()

num_var_df.describe(percentiles=[0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.75,0.8,0.85,0.9,0.95,0.99])

"""From the above, there are few variables which are having zero values. Hence we are droping them."""

housePrice_df.drop(['BsmtFinSF2','LowQualFinSF','EnclosedPorch','3SsnPorch','ScreenPorch','PoolArea','MiscVal'],axis=1,inplace=True)

cat_var

#Extracting numerical / contineous variables for further analysis
num_var= [i for i in housePrice_df.columns if housePrice_df.dtypes[i]!='object']
cat_var = [i for i in housePrice_df.columns if housePrice_df.dtypes[i] =='object']
num_var

"""## Data preparation"""

# Splitting the data into train and test data
housePrice_df_train,housePrice_df_test = train_test_split(housePrice_df, train_size=0.7,random_state=100)

# Scaling the continuous variables.
scaler = StandardScaler()
housePrice_df_train[['LotFrontage', 'LotArea', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'TotalBsmtSF', 'CentralAir',
 '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'YrSold', 'SalePrice', 'HouseAge', 'House_RemodelAge']] = scaler.fit_transform(housePrice_df_train[['LotFrontage', 'LotArea', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'TotalBsmtSF', 'CentralAir',
 '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'YrSold', 'SalePrice', 'HouseAge', 'House_RemodelAge']])
housePrice_df_test[['LotFrontage', 'LotArea', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'TotalBsmtSF', 'CentralAir',
 '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'YrSold', 'SalePrice', 'HouseAge', 'House_RemodelAge']] = scaler.fit_transform(housePrice_df_test[['LotFrontage', 'LotArea', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'TotalBsmtSF', 'CentralAir',
 '1stFlrSF', '2ndFlrSF', 'GrLivArea', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'YrSold', 'SalePrice', 'HouseAge', 'House_RemodelAge']])

y_train = housePrice_df_train.pop('SalePrice')
X_train = housePrice_df_train

y_test = housePrice_df_test.pop('SalePrice')
X_test = housePrice_df_test

"""## Ridge Regression

Now We will perform the Ridge regression using negative mean absolute error.
"""

# creating some list of alpha values to perform the regression
params = {'alpha': [0.01,0.1,1,10,20,50,75,100]}
#ridge regression
ridge = Ridge()
# cross validation
folds = 10
#creating cross  validation model using Ridge regression with score of negative mean absolute error.
cv_model = GridSearchCV(estimator = ridge,
                        param_grid = params,
                        scoring= 'neg_mean_absolute_error',
                        cv = folds,
                        return_train_score=True,
                        verbose = 1)
cv_model.fit(X_train, y_train)

# copying CV model results into dataframe .
cv_model_results = pd.DataFrame(cv_model.cv_results_)
cv_model_results['param_alpha'] = cv_model_results['param_alpha'].astype('float32')
#reading the top 5 rows of CV Model result data frame
cv_model_results.head()

# plotting the test and train sets of Aplha and mean error
cv_model_results['param_alpha'] = cv_model_results['param_alpha'].astype('int32')

# plotting between the alpha and Negative Mean absolute Error for Train and Test sets
plt.xlabel('alpha')
plt.ylabel('Negative Mean Absolute Error')
plt.title("Negative Mean Absolute Error Vs Alpha")
plt.plot(cv_model_results['param_alpha'], cv_model_results['mean_train_score'])
plt.plot(cv_model_results['param_alpha'], cv_model_results['mean_test_score'])
plt.legend(['train score', 'test score'], loc='upper right')

# Finding out the best score and Optimum value of alpha
print(cv_model.best_estimator_)
print('best alpha value:',cv_model.best_params_)
print('Best score:',cv_model.best_score_)

"""### Ridge Regression using R2 Score

Now We will perform the Ridge regression using R2 Score.
"""

# creating some list of alpha values to tune the regression further
params = {'alpha': [0.01,0.1,1,10,20,50,75,100]}
ridge = Ridge()
# cross validation
folds = 10
#creating the cross validation model using r2 score
cv_model_r2 = GridSearchCV(estimator = ridge,
                        param_grid = params,
                        scoring= 'r2',
                        cv = folds,
                        return_train_score=True,
                        verbose = 1)
cv_model_r2.fit(X_train, y_train)

#creating CV model results into data frame
cv_Model_results_r2 = pd.DataFrame(cv_model_r2.cv_results_)
cv_Model_results_r2['param_alpha'] = cv_Model_results_r2['param_alpha'].astype('float32')
#reading the top 5 rows of data frame
cv_Model_results_r2.head()

# plotting test and train scoes with alpha and r2 score
cv_Model_results_r2['param_alpha'] = cv_Model_results_r2['param_alpha'].astype('int32')

# plotting between the alpha and R2 Score for train and test sets
plt.xlabel('alpha')
plt.ylabel('R2 Score')
plt.title("R2 Score Vs alpha")
plt.plot(cv_Model_results_r2['param_alpha'], cv_Model_results_r2['mean_train_score'])
plt.plot(cv_Model_results_r2['param_alpha'], cv_Model_results_r2['mean_test_score'])
plt.legend(['train score', 'test score'], loc='upper right')

# Finding out the best score and Optimum value of alpha
print(cv_model_r2.best_estimator_)
print('best alpha value:',cv_model_r2.best_params_)
print('Best score:',cv_model_r2.best_score_)

"""From the above,the alpha value is 10 from the both r2 score and negative mean absolute error. Hence we are considering alpha value =10 for the Ridge regression.

    alpha = 10
"""

# Ridge Regression Model with alpha = 10:
ridge = Ridge(alpha = 10)
ridge.fit(X_train,y_train)
# r2 score for train set
y_pred_train = ridge.predict(X_train)
print('r2 Score for Train is ',r2_score(y_train,y_pred_train))
#r2 score for test set
y_pred_test = ridge.predict(X_test)
print('r2 Score for test is ',r2_score(y_test,y_pred_test))

#creating coeffcients for the ridge regression
model_parameter = list(ridge.coef_)
model_parameter.insert(0,ridge.intercept_)
cols = housePrice_df.columns
cols.insert(0,'const')
ridge_coef = pd.DataFrame(list(zip(cols,model_parameter)))
ridge_coef.columns = ['Features','Coefficient']

#selecting the top 10 variables
ridge_coef[:10].sort_values(by='Coefficient',ascending=False)

ridge_rmse = Ridge(alpha=10)
ridge_rmse.fit(X_train,y_train)
#mean squared error for train
y_pred_train_mean = ridge_rmse.predict(X_train)
print('Mean squared error for train is ',np.sqrt(mean_squared_error(y_train, y_pred_train_mean)))
# mean squared error for test
y_pred_test_mean = ridge_rmse.predict(X_test)
print('Mean squared error for test is ', np.sqrt(mean_squared_error(y_test, y_pred_test_mean)))

"""## Lasso Regression

Now we will perform the Lasso regression using negative Mean Absolute error
"""

lasso = Lasso()
#Creating list of alpha values
param = {'alpha': [0.0001,  0.001,  0.002,  0.005, 0.01]}
folds = 10
# cross validation
cv_model_lasso = GridSearchCV(estimator = lasso,
                        param_grid = param,
                        scoring= 'neg_mean_absolute_error',
                        cv = folds,
                        return_train_score=True,
                        verbose = 1)

cv_model_lasso.fit(X_train, y_train)

#Creating the results dataframe.
cv_model_results_lasso = pd.DataFrame(cv_model_lasso.cv_results_)
#reading top 5 rows
cv_model_results_lasso.head()

# plotting mean test and train scores with alpha
cv_model_results_lasso['param_alpha'] = cv_model_results_lasso['param_alpha'].astype('float32')
# plotting between the negative mean absolute error and alpha
plt.plot(cv_model_results_lasso['param_alpha'], cv_model_results_lasso['mean_train_score'])
plt.plot(cv_model_results_lasso['param_alpha'], cv_model_results_lasso['mean_test_score'])
plt.xlabel('alpha')
plt.ylabel('Negative Mean Absolute Error')
plt.title("Negative Mean Absolute Error and alpha")
plt.legend(['train score', 'test score'], loc='upper right')

# finding out the best score and optimum value of alpha.
print(cv_model_lasso.best_estimator_)
print('best alpha value:',cv_model_lasso.best_params_)
print('Best score:',cv_model_lasso.best_score_)

"""### Lasso Regression using R2 Score

Now we will perform the Lasso Regression using R2 Score
"""

# list of alphas to tune the model
params = {'alpha': [0.0001, 0.001, 0.002, 0.005, 0.01]}
lasso = Lasso()
# cross validation
folds=10
cv_model_lasso_r2 = GridSearchCV(estimator = lasso,
                        param_grid = params,
                        scoring= 'r2',
                        cv = folds,
                        return_train_score=True,
                        verbose = 1)

cv_model_lasso_r2.fit(X_train, y_train)

#Creating the results dataframe.
cv_model_lasso_r2_results = pd.DataFrame(cv_model_lasso_r2.cv_results_)
#reading the top 5 rows
cv_model_lasso_r2_results.head()

# plotting mean test and train scoes with alpha
cv_model_lasso_r2_results['param_alpha'] = cv_model_lasso_r2_results['param_alpha'].astype('float32')

# plotting between R2Score and alpha
plt.xlabel('alpha')
plt.ylabel('R2')
plt.title("R2 and alpha")
plt.plot(cv_model_lasso_r2_results['param_alpha'], cv_model_lasso_r2_results['mean_train_score'])
plt.plot(cv_model_lasso_r2_results['param_alpha'], cv_model_lasso_r2_results['mean_test_score'])
plt.legend(['train score', 'test score'], loc='upper right')

# finding out the best score and optimum value of alpha.
print(cv_model_lasso_r2.best_estimator_)
print('best alpha value:',cv_model_lasso_r2.best_params_)
print('best score:',cv_model_lasso_r2.best_score_)

"""From the above,the alpha value is 10 from the both r2 score and negative mean absolute error. Hence we are considering alpha value =0.001 for the lasso regression.

    alpha = 0.001
"""

#proceeding with the alpha value 0.01
lasso = Lasso(alpha=0.001)
lasso.fit(X_train,y_train)

y_train_pred = lasso.predict(X_train)
y_test_pred = lasso.predict(X_test)

print('r2 Score for Train is ',r2_score(y_true=y_train,y_pred=y_train_pred))
print('r2 Score for Test is ',r2_score(y_true=y_test,y_pred=y_test_pred))

model_param = list(lasso.coef_)
model_param.insert(0,lasso.intercept_)
cols = housePrice_df.columns
cols.insert(0,'const')
lasso_coef = pd.DataFrame(list(zip(cols,model_param)))
lasso_coef.columns = ['Features','Coefficient']

#coefficients
lasso.coef_

lasso_coef[:10].sort_values(by='Coefficient',ascending=False)

lasso_rmse = Lasso(alpha=0.001)
lasso_rmse.fit(X_train,y_train)

y_pred_train = lasso_rmse.predict(X_train)
print('Mean Squared error for Train is ',np.sqrt(mean_squared_error(y_train, y_pred_train)))

y_pred_test = lasso_rmse.predict(X_test)
print('Mean Squared error for Test is ',np.sqrt(mean_squared_error(y_test, y_pred_test)))

plt.figure(figsize=(20, 10))
coefs = pd.Series(lasso.coef_)

imp_coefs = pd.concat([coefs.sort_values().head(10),
                     coefs.sort_values().tail(10)])
imp_coefs.plot(kind = "barh")
plt.title("Features importance in the Lasso Model")
plt.show()



"""## Subjective Questions

#### Question 1
What is the optimal value of alpha for ridge and lasso regression? What will be the changes in the model if you choose double the value of alpha for both ridge and lasso? What will be the most important predictor variables after the change is implemented?

From the above, We got the following alpha optimal values:

    Alpha = 10 (Ridge)

    Alpha = 0.001(Lasso)

Now we are Implementing double the value of alpha for both models, hence the alpha values will be the following for the Ridge and Lasso and the predictions will be as follows:
    
    Alpha = 20 (Ridge)
    
    Alpha = 0.002 (Lasso)

Considering the above, we are proceeding with alpha = 20 and continued with Ridge regression
"""

# rebuilding the Ridge Regression, with alpha = 20
ridge_new = Ridge(alpha = 20)
ridge_new.fit(X_train,y_train)
# r2 score for train set
y_pred_train_new = ridge_new.predict(X_train)
print('r2 Score for Train is ',r2_score(y_train,y_pred_train_new))
#r2 score for test set
y_pred_test_new = ridge_new.predict(X_test)
print('r2 Score for test is ',r2_score(y_test,y_pred_test_new))

model_parameter_new = list(ridge_new.coef_)
model_parameter_new.insert(0,ridge_new.intercept_)
cols = housePrice_df.columns
cols.insert(0,'constant')
ridge_coef_new = pd.DataFrame(list(zip(cols,model_parameter_new)))
ridge_coef_new.columns = ['Features','Coefficient']

ridge_coef_new[:10].sort_values(by='Coefficient',ascending=False)#.head(10)

#rebuilding lasso regression model with alpha 0.002
lasso_new = Lasso(alpha=0.002)
lasso_new.fit(X_train,y_train)
y_train_pred_new1 = lasso_new.predict(X_train)
y_test_pred_new1 = lasso_new.predict(X_test)
print('r2 Score for Train set',r2_score(y_true=y_train,y_pred=y_train_pred_new1))
print('r2 score for Test set',r2_score(y_true=y_test,y_pred=y_test_pred_new1))

model_lasso_new = list(lasso_new.coef_)
model_lasso_new.insert(0,lasso_new.intercept_)
cols = housePrice_df.columns
cols.insert(0,'const')
lasso_coef_new = pd.DataFrame(list(zip(cols,model_lasso_new)))
lasso_coef_new.columns = ['Features','Coefficient']
lasso_coef_new[:10].sort_values(by='Coefficient',ascending=False)

"""#### Question 2
You have determined the optimal value of lambda for ridge and lasso regression during the assignment. Now, which one will you choose to apply and why?

From the above, I got the following optimal values of alpha:

    Alpha = 10 (Ridge)

    Alpha = 0.001 (Lasso)

I will apply the Lasso regression model with 0.001 value of Alpha since it performs the feature selection by way of reducing some of the variable coefficients to zero which is very useful for us in this case since we have around 200 independant features here in the dataset.
"""

model_param = list(lasso.coef_)
model_param.insert(0,lasso.intercept_)
cols = housePrice_df.columns
cols.insert(0,'const')
lasso_coef = pd.DataFrame(list(zip(cols,model_param)))
lasso_coef.columns = ['Features','Coef']
lasso_coef[:10].sort_values(by='Coef',ascending=False)

"""#### Question 3

After building the model, you realised that the five most important predictor variables in the lasso model are not available in the incoming data. You will now have to create another model excluding the five most important predictor variables. Which are the five most important predictor variables now?
"""

housePrice_df_new = housePrice_df.drop(['YearRemodAdd','GrLivArea','MasVnrArea','CentralAir','1stFlrSF'],axis=1)
housePrice_df_new.head()



# Splitting the data set into train and test set
housePrice_df_new_train,housePrice_df_new_test = train_test_split(housePrice_df_new, train_size=0.7,random_state=100)

# Scaling the continuous variables.
scaler = StandardScaler()
housePrice_df_new_train[['LotFrontage', 'LotArea', 'YearBuilt', 'TotalBsmtSF',
  '2ndFlrSF',  'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'YrSold', 'SalePrice', 'HouseAge', 'House_RemodelAge']] = scaler.fit_transform(housePrice_df_new_train[['LotFrontage', 'LotArea', 'YearBuilt',  'TotalBsmtSF',
  '2ndFlrSF',  'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'YrSold', 'SalePrice', 'HouseAge', 'House_RemodelAge']])
housePrice_df_new_test[['LotFrontage', 'LotArea', 'YearBuilt', 'TotalBsmtSF',
  '2ndFlrSF',  'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'YrSold', 'SalePrice', 'HouseAge', 'House_RemodelAge']] = scaler.fit_transform(housePrice_df_new_test[['LotFrontage', 'LotArea', 'YearBuilt',  'TotalBsmtSF',
  '2ndFlrSF',  'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'YrSold', 'SalePrice', 'HouseAge', 'House_RemodelAge']])

y_train_new = housePrice_df_new_train.pop('SalePrice')
X_train_new = housePrice_df_new_train

y_test_new = housePrice_df_new_test.pop('SalePrice')
X_test_new = housePrice_df_new_test

"""From the above, it is clear that we need to find out the five most important variables, hence we are building the lasso regression

## Lasso Regression - Modified
"""

lasso_modified = Lasso()
param = {'alpha': [0.0001, 0.001, 0.01]}
folds = 10
# cross validation
lasso_cv_model_modified = GridSearchCV(estimator = lasso,
                        param_grid = param,
                        scoring= 'neg_mean_absolute_error',
                        cv = folds,
                        return_train_score=True,
                        verbose = 1)

lasso_cv_model_modified.fit(X_train_new, y_train_new)

#Creating the results dataframe.
lasso_cv_modified_results = pd.DataFrame(lasso_cv_model_modified.cv_results_)
#reading the results
lasso_cv_modified_results.head()

# plotting mean test and train scores with alpha
lasso_cv_modified_results['param_alpha'] = lasso_cv_modified_results['param_alpha'].astype('float32')
# plotting between the negative mean absolute error and alpha
plt.plot(lasso_cv_modified_results['param_alpha'], lasso_cv_modified_results['mean_train_score'])
plt.plot(lasso_cv_modified_results['param_alpha'], lasso_cv_modified_results['mean_test_score'])
plt.xlabel('alpha')
plt.ylabel('Negative Mean Absolute Error')
plt.title("Negative Mean Absolute Error and alpha")
plt.legend(['train score', 'test score'], loc='upper right')

# Printing the best score and optimum value of alpha.
print(lasso_cv_model_modified.best_estimator_)
print('Best alpha value:',lasso_cv_model_modified.best_params_)
print('Best score:',lasso_cv_model_modified.best_score_)

lasso_new_modified = Lasso(alpha=0.001)
lasso_new_modified.fit(X_train_new,y_train_new)

y_train_new_pred = lasso_new_modified.predict(X_train_new)
y_test_new_pred = lasso_new_modified.predict(X_test_new)

print('r2 Score for Train:',r2_score(y_true=y_train_new,y_pred=y_train_new_pred))
print('r2 Score for Test:',r2_score(y_true=y_test_new,y_pred=y_test_new_pred))

model_param = list(lasso.coef_)
model_param.insert(0,lasso.intercept_)
cols = housePrice_df_new.columns
cols.insert(0,'const')
lasso_coef = pd.DataFrame(list(zip(cols,model_param)))
lasso_coef.columns = ['Features','Coefficient']

lasso_coef[:10].sort_values(by='Coefficient',ascending=False)

